/** @type {import('jest').Config} */
module.exports = {
  preset: 'jest-expo',
  globalSetup: '<rootDir>/jest.globalSetup.js',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  // Native projects are regenerated by `expo prebuild` and may exist locally.
  testPathIgnorePatterns: ['/node_modules/', '/ios/', '/android/', '/.expo/'],
  clearMocks: true,
};
